version: "3.8"

services:
  db:
    container_name: money_processing_db
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
    networks:
      - money_processing_service

  admin:
    container_name: money_processing_db_web_adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8090:8080
    networks:
      - money_processing_service

  app:
    image: darksoul94/money-processing-sevice:latest
    build: .
    environment:
      - DBHost=db
      - DBPort=5432
      - DBLogin=postgres
      - DBPass=postgres
    restart: always
    depends_on:
      - db
    ports:
      - 8888:8888
    networks:
      - money_processing_service

networks:
  money_processing_service:
